version: '2.3'
services:
  exo:
    image: exoplatform/exo-community:6.3
    environment:
      EXO_PROXY_VHOST: localhost
      EXO_PROXY_PORT: 80
      EXO_DB_HOST: mysql
      EXO_PROXY_SSL: "false"
      EXO_DB_TYPE: mysql
      EXO_DB_NAME: exo
      EXO_DB_USER: exo
      EXO_DB_PASSWORD: my-secret-pw
      EXO_ADDONS_LIST:
      EXO_JVM_LOG_GC_ENABLED: "true"
      EXO_ES_HOST: es
      EXO_MONGO_HOST: mongo
      EXO_MONGO_PORT: 27017
      EXO_MONGO_DB_NAME: chat
      EXO_DEBUG_ENABLED: "true"
    expose:
      - "8080"
      - "8000"
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - exo_data:/srv/exo
      - exo_logs:/var/log/exo
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: my-super-secret-pw
      MYSQL_DATABASE: exo
      MYSQL_USER: exo
      MYSQL_PASSWORD: my-secret-pw
    volumes:
      - mysql_data:/var/lib/mysql
  es:
    image: exoplatform/elasticsearch:2.0.3
    volumes:
      - search_data:/usr/share/elasticsearch/data:rw
    environment:
      - ES_JAVA_OPTS=-Xms2048m -Xmx2048m
      - node.name=exo
      - cluster.name=exo
      - cluster.initial_master_nodes=exo
      - network.host=_site_

  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db:rw
      - ./conf/mongo.conf:/etc/mongod.conf:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "5"

volumes:
  exo_data:
  exo_logs:
  mysql_data:
  search_data:
  mongo_data: